version: '3.4'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: dist
    ports:
      - '8000:80'
  server-json:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - PORT=6060
    ports:
      - '6060:6060'
    command: yarn start:server
